<a href="https://colab.research.google.com/github/PrzemyslawCh/PyTorch_Course/blob/main/Pytorch_Fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Intro to Tensors

### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get Tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8], [9, 10]])

In [ ]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

In [ ]:
TENSOR = torch.tensor([[[1,2,4],
                        [3,4,2],
                        [4,2,2]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape


torch.Size([1, 3, 3])

In [ ]:
TENSOR2 = torch.tensor([[1,2,3,4], [1,2,3,4], [1,2,3,4]])

In [ ]:
TENSOR2.ndim

2

In [ ]:
TENSOR3 = torch.tensor([[[1,2,3,4], [1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4], [1,2,3,4]]])

In [ ]:
TENSOR2.shape

torch.Size([3, 4])

In [ ]:
TENSOR3.shape


torch.Size([3, 3, 4])

In [ ]:
TENSOR3.ndim

3

### Random tensors

### Why radnom tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of radnom numebrs anbd then dsjuts those random nmumbers to better represents the data.

''Starts with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ''

Torch random tensors  

In [ ]:
# Create a random tensors of size(shape) (3 ,4)
random_tensor = torch.rand(1, 1, 12)

In [ ]:
random_tensor

tensor([[[0.6988, 0.5931, 0.2899, 0.6924, 0.1007, 0.2115, 0.6255, 0.1166,
          0.1111, 0.4486, 0.9183, 0.3825]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape


torch.Size([1, 1, 12])

In [ ]:
# Create a random tensor with similar shape to an image tensor

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)

In [ ]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and ones

In [ ]:
# Create a tensor of all zeros

In [ ]:
zeros = torch.zeros(size=(3, 4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.float32

torch.float32

In [ ]:
ones.dtype

torch.float32

### Creating range of tensors and tensors-lile

In [ ]:
# Torch.range() and get deprecated messega, ise torch.arange()

In [ ]:
one_to_ten = torch.arange(start=1,end = 10, step=1)

In [ ]:
one_to_ten


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating tensors like

In [ ]:
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zereos = torch.zeros_like(input=one_to_ten)

In [ ]:
ten_zereos

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PytTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensor not on the right device

In [ ]:
# Float 32 tesnor

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What type is the tensor
                               device = None, # What device is your tensor on
                              requires_grad=False) # Whether or not track gredients with this tensors operations

In [ ]:
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 5, 8], dtype = torch.long)


In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 30., 72.])

### Gettuing infomrmation from tensors (tensors atrributes)

1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from tensor, can use tensor.shape
3. Tensor not on the right device  to get device from tensor, can use tensor.device

In [ ]:
# Create a tensor

In [ ]:
some_tensor = torch.rand(3, 4)

In [ ]:
some_tensor

tensor([[0.7316, 0.1598, 0.1414, 0.5612],
        [0.3476, 0.0672, 0.9977, 0.8125],
        [0.7197, 0.8014, 0.4276, 0.2789]])

In [ ]:
print(some_tensor)

tensor([[0.7316, 0.1598, 0.1414, 0.5612],
        [0.3476, 0.0672, 0.9977, 0.8125],
        [0.7197, 0.8014, 0.4276, 0.2789]])


In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


In [ ]:
print(f"Device tensor is on: {some_tensor.device}")

Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

* add, sub, multiplicatio(element-wise), division, Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor + 100



tensor([101, 102, 103])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor * 100



tensor([100, 200, 300])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Try out Pytorch in-build functions

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplications
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* '(3, 2) @ (3, 2)' wont work
* '(2, 3 ) @ (3, 2)' will work
* '(3,2) @ (2, 3)' will work

2. The resulting matrix has the shape of the **outer dimesnions**:
* '(2, 3) @ (3, 2)' -> '(2, 2)'

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [ ]:
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication

In [ ]:
%%time
tensor.matmul(tensor)

CPU times: user 499 µs, sys: 71 µs, total: 570 µs
Wall time: 7.67 ms


tensor(14)

In [ ]:
# Matrix multiplicatino by hand

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.37 ms, sys: 984 µs, total: 2.36 ms
Wall time: 7.71 ms


In [ ]:
### Shape

### One of the most common error in machine learning

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7, 8],
                        [9 , 10],
                        [10,11]])

In [ ]:
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it is an alieas for matmul

torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix or tensor shape issues we can manipulate the shape one of our tensors usind transpose

A **Transpose** switches the axes or dimesnions of a given tensor

In [ ]:
tensor_B.T.shape


torch.Size([2, 3])

In [ ]:
tensor_B

tensor([[ 7,  8],
        [ 9, 10],
        [10, 11]])

In [ ]:
### Finding min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean  note: the torch.mean() function requires a tesnor of float32 datatype to work
x.type(torch.float32).mean()


tensor(46.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [ ]:
torch.argmin(x), x.argmin() # argument with min value

(tensor(0), tensor(0))

In [ ]:
torch.argmax(x)

tensor(9)

In [ ]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Reshaping, stacking, squeezing and unsquzeezing tensors

* Reshaping - reshapes an input tensor to a definded shape
* View - Return of a view of an input of tensor od certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other
* Squeeze - removes all '1' dimensions from tensor
* Unsqueeze - add a '1' dimension to target tensor
* Permute - retunr a view of the input with dimensions permuted (swapped) in a certain way



In [ ]:
# Let's create tesnor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view

In [ ]:
z = x.view(1, 9)

In [ ]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because view of a tensor shares the same memory as the original)
z[:, 0]
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)

In [ ]:
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all sible dimesions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

x = torch.zeros(2, 1, 2, 1, 2)
x.size()

y = torch.squeeze(x)
y.size()

y = torch.squeeze(x, 0)
y.size()

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

 New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


torch.Size([2, 1, 2, 1, 2])

In [ ]:
# torch.unsqueezed() - adds a single diemnsion to a target tesnor at aspecific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimesnion with unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\n New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
y = torch.squeeze(x, 1)

In [ ]:
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.permute  rearranges the dimensions of a target tensor in specified order
# You can use it with images
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
# Permute the original tensor to reaarrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]

tensor(0.1876)

In [ ]:
x_permuted[0,0,0]

tensor(0.1876)

## Indexing (selecting data from tesnors)

Indexing with Pytorch is similat indexing with NumPy

In [ ]:
# Creating a tesnor
import torch

In [ ]:
x = torch.arange(1, 10).reshape(1, 3 , 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
# Let's idnex on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket
x[0][0][1]

tensor(2)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ':' to sellect "all" of target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values 0th and 1st dimesnions but only index 1 of 2nd dimension

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but lnly the 1 index value of 1st and 2nd dimesnion

In [ ]:
x[:, 1, 1], x[0,1,1]

(tensor([5]), tensor(5))

In [ ]:
# Get index 0 if 0th and 1st dimenion and all values of 2nd dimension

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tnsors & NumPy

NumP is a popular sciantefic Python numerical computing libraray

And because of this Pytoerch has functionality to interact with it

*Data in Numpy, want in Pytorch tesnor -> 'torch.from_numpy(ndarray)
*Pytorch tensor -> Numpt ->torch.'

In [ ]:
# Numpyarray to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when comverting from numpy pytorch, pytoch
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype


dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# change the value of array, waht will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor



(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))


## Reproducibility (trying to take random out of random)

In short how a neural network learns:

'start with random numbers' -> tensor operations -> update radnom numbers to try and make them better representation of the data -> again -> again

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavor" the randommness



In [ ]:
import torch

# Create two random tensors

random_Tensor_A = torch.rand(3, 4)
random_Tensor_B = torch.rand(3, 4)

print(random_Tensor_A)
print(random_Tensor_B)
print(random_Tensor_A == random_Tensor_B)

tensor([[0.0541, 0.2831, 0.7816, 0.1202],
        [0.3171, 0.0133, 0.3526, 0.2454],
        [0.9066, 0.6672, 0.1958, 0.3022]])
tensor([[0.8266, 0.5269, 0.4312, 0.0973],
        [0.0454, 0.2288, 0.9132, 0.1953],
        [0.7847, 0.0961, 0.5697, 0.9712]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed

Random_Seed = 42

torch.manual_seed(Random_Seed)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(Random_Seed)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_D == random_tensor_C)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPU'S (and making daster computations)

GPU's = faster on computtaions numbers tahnks to cuda nvidia hardware pytoch working behind the scenes



### 1. Getting a CPU

1. Easiest - use google colab for a free GPU (options to upgrade as well)
2. You can use yours - takes a little bit of setup and np.require the investments of purcheses
3. Use cloud computing - GCP, AWS, AZURE these serivces allow you rent computers on the cloud and
access them

FOR 2, 3 Pytoch + GPU drivers takes some time to set-up with CUDA go to cuda documentation.

In [ ]:
!nvidia-smi

Wed Mar  1 11:50:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P0    28W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with pytorch

In [ ]:
# Check for GPU access with Pytorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practise to setup device agnostic code:

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models on the GPU)

The reason we want out tensors/models on the GPU is because using GPU in daster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (ifavailable)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensor back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it ti NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# To fix it we can first set it ti the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
import torch